// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrjf_RoXL4CJp43ZZjlwQv8RYtLWx9pqE',
    appId: '1:988033976327:web:27a4ed1763e6feea92c2a2',
    messagingSenderId: '988033976327',
    projectId: 'bingo-cef6d',
    authDomain: 'bingo-cef6d.firebaseapp.com',
    databaseURL: 'https://bingo-cef6d-default-rtdb.firebaseio.com',
    storageBucket: 'bingo-cef6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwilyah1XMiVO9VDeyIG2ysgPpj2j9LME',
    appId: '1:988033976327:android:0557c8fd253892eb92c2a2',
    messagingSenderId: '988033976327',
    projectId: 'bingo-cef6d',
    databaseURL: 'https://bingo-cef6d-default-rtdb.firebaseio.com',
    storageBucket: 'bingo-cef6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP6zh7aa9EgGWhtcNDsxP4iS6Y-BbFzD4',
    appId: '1:988033976327:ios:6ceb07baf28588b992c2a2',
    messagingSenderId: '988033976327',
    projectId: 'bingo-cef6d',
    databaseURL: 'https://bingo-cef6d-default-rtdb.firebaseio.com',
    storageBucket: 'bingo-cef6d.firebasestorage.app',
    iosBundleId: 'com.example.biongoAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP6zh7aa9EgGWhtcNDsxP4iS6Y-BbFzD4',
    appId: '1:988033976327:ios:6ceb07baf28588b992c2a2',
    messagingSenderId: '988033976327',
    projectId: 'bingo-cef6d',
    databaseURL: 'https://bingo-cef6d-default-rtdb.firebaseio.com',
    storageBucket: 'bingo-cef6d.firebasestorage.app',
    iosBundleId: 'com.example.biongoAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8oVR-oUu1k-woaCqzR0cc-8caobGzTnc',
    appId: '1:988033976327:web:a1fdf17afd234edf92c2a2',
    messagingSenderId: '988033976327',
    projectId: 'bingo-cef6d',
    authDomain: 'bingo-cef6d.firebaseapp.com',
    databaseURL: 'https://bingo-cef6d-default-rtdb.firebaseio.com',
    storageBucket: 'bingo-cef6d.firebasestorage.app',
  );
}
